version: "3.9"
services:
  app:
    container_name: vyrill
    build:
      context: .
      target: local
    image: vyrill:local
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.aws:/root/.aws
    environment:
      NODE_ENV: dev
      STAGE: ${STAGE}
      AWS_REGION: ${AWS_REGION}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    #command: node --inspect-brk=0.0.0.0:9229 /app/node_modules/.bin/serverless offline start --host 0.0.0.0 --httpPort 4000 --printOutput --stage dev --region us-east-1 --profile my-profile
    #todo: Enable debuging capabilities via Docker

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    depends_on:
      - app
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: app:4000
      NGROK_AUTH: ${NGROK_AUTH} # https://dashboard.ngrok.com/get-started/your-authtoken
